spring:
    application:
        name: Ethereum
    messages:
        basename: i18n/messages
    thymeleaf:
        mode: XHTML
    datasource:
        url: jdbc:mysql://localhost:3306/switch
        username: switch
        password: switch
        driver-class-name: com.mysql.jdbc.Driver
server:
    port: 8082
    session:
        cookie:
            http-only: true
debug: true

logging:
  level:
    org.springframework.security: DEBUG

cloud:
    cinder:
        peapol:
            login-url: http://localhost:9999/login
        switch:
            base-url: http://localhost:8080
        airstrip:
            base-url: http://localhost:8081
        ethereum:
            base-url: http://localhost:8082
